branch-defaults:
  main:
    environment: photoshare-api
    group_suffix: null

deploy:
  artifact: Dockerrun.aws.json

global:
  application_name: photoshare
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application